---
title: "practica_final_rii"
author: "Juliana Cruz"
date: "2023-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(readxl)
library(tidyr)# doma de datos
library(janitor) #limpieza de datos
library(lubridate)
library(hms)
```

# Preparación y limpieza de Datos:

2.1 Lectura de datos en R 

```{r include=FALSE}
terremotos_profundidad <- read_csv("https://raw.githubusercontent.com/isa229/programacion_analisis_datos_ii/main/terremotos_profundidad.csv")
terremotos_magnitud <- read_csv("https://raw.githubusercontent.com/isa229/programacion_analisis_datos_ii/main/terremotos_magnitud.csv")
```
2.2 Traducción de variables al español
_
2.2.1 Renombrar variables de terremotos_maginitud

```{r}
terremotos_magnitud <- terremotos_magnitud |> 
 rename(Magnitud = Magnitude,
        Tipo_magnitud = `Magnitude Type`)

```

2.2.2

```{r}
terremotos_profundidad <- terremotos_profundidad |> 
 rename(Fecha = Date,
        Hora = Time,
        Latitud = Latitude,
        Longitud = Longitude,
        Tipo = Type, 
        Profundidad = Depth,
        Error_profundidad = `Depth Error`)
```

2.3 Eliminación de filas duplicadas


```{r}
terremotos_magnitud <- terremotos_magnitud |> 
  distinct()
```


```{r}
terremotos_profundidad <- terremotos_profundidad |> 
  distinct()
```

2.4 Transformación de tipos de variables 

```{r}
terremotos_profundidad <- terremotos_profundidad |> 
  mutate(Fecha = mdy(Fecha))
```

2.5. Transformación de datos

```{r}
dup_terremotos_profundidad  <- terremotos_profundidad |>  
  select(Tipo) |> 
  distinct()

terremotos_profundidad <- terremotos_profundidad |> 
  mutate(Tipo = str_to_title(Tipo))

```

2.6. Creación de columnas adicionales

```{r}
terremotos_profundidad <- terremotos_profundidad |> 
  mutate(Mes = format(Fecha, "%B"))

terremotos_profundidad <- terremotos_profundidad |> 
  mutate(Anio = format(Fecha, "%Y"))
```

2.7. Unir conjunto de datos

```{r}
datos_terremotos <- left_join(terremotos_magnitud, terremotos_profundidad, by = "ID")
```

2.8. Eliminar columnas vacías

```{r}
datos_terremotos <- datos_terremotos |> 
  remove_empty(which = c("rows", "cols"))

datos_terremotos <- subset(datos_terremotos, select = -...1.x)

datos_terremotos <- subset(datos_terremotos, select = -...1.y)
```


